# configuration for <https://github.com/crate-ci/committed>
## see the reference: <https://github.com/crate-ci/committed/blob/master/docs/reference.md>

# commit message rules
imperative_subject = true
line_length = 72
style = "conventional"
subject_capitalized = false
subject_length = 0            # disable the check
subject_not_punctuated = true

# commit types
merge_commit = false
no_fixup = true
no_wip = true
