# NOTE: This project does not attribute contributors individually. Instead refer to `git log --format="%an <%aE>" | sort -u` for a list of individual contributors.
SPDX-PackageDownloadLocation = "https://gitlab.archlinux.org/archlinux/alpm/alpm"
SPDX-PackageName = "alpm"
SPDX-PackageSupplier = "Arch Linux"
version = 1

[[annotations]]
SPDX-FileCopyrightText = "ALPM Contributors"
SPDX-License-Identifier = "Apache-2.0 OR MIT"
path = ["**.ers", "**.rs"]
precedence = "aggregate"

[[annotations]]
SPDX-FileCopyrightText = "ALPM Contributors"
SPDX-License-Identifier = "CC0-1.0"
path = [
    "**.bash",
    "**.mtree",
    "**.pkgbuild",
    "**.sh",
    "**.snap",
    "**.srcinfo",
    "**.stub",
    "**.toml",
    "*.json",
    "*.lock",
    "*.yml",
    ".codespellrc",
    ".env",
    ".gitignore",
    ".gitlab/CODEOWNERS",
    ".lycheeignore",
    "alpm-srcinfo/tests/files/*.srcinfo",
    "justfile",
    "voa-core/tests/README",
]
precedence = "aggregate"

[[annotations]]
SPDX-FileCopyrightText = "ALPM Contributors"
SPDX-License-Identifier = "CC-BY-SA-4.0"
path = ["**.md"]
precedence = "aggregate"
