# NOTE: This project does not attribute contributors individually. Instead refer to `git log --format="%an <%aE>" | sort -u` for a list of individual contributors.
SPDX-PackageDownloadLocation = "https://gitlab.archlinux.org/archlinux/alpm/alpm"
SPDX-PackageName = "alpm"
SPDX-PackageSupplier = "Arch Linux"
version = 1

[[annotations]]
SPDX-FileCopyrightText = "ALPM Contributors"
SPDX-License-Identifier = "Apache-2.0 OR MIT"
path = ["**.ers", "**.py", "**.pyi", "**.rs"]
precedence = "aggregate"

[[annotations]]
SPDX-FileCopyrightText = "ALPM Contributors"
SPDX-License-Identifier = "CC0-1.0"
path = [
    "**.bash",
    "**.desc",
    "**.ftl",
    "**.json",
    "**.jsonc",
    "**.lock",
    "**.mtree",
    "**.pkgbuild",
    "**.sh",
    "**.snap",
    "**.srcinfo",
    "**.stub",
    "**.toml",
    "**/.gitignore",
    "**justfile",
    "*.yml",
    ".cargo/runner.sh",
    ".codespellrc",
    ".gitlab/CODEOWNERS",
    ".gitmodules",
    ".lycheeignore",
    ".mailmap",
    ".shellcheckrc",
    "alpm-db/tests/parse_errors/files/*.files",
    "alpm-repo-db/tests/parse_errors/files/*.files",
    "alpm-soname/tests/test_files/*",
    "alpm-srcinfo/tests/files/*.srcinfo",
]
precedence = "aggregate"

[[annotations]]
SPDX-FileCopyrightText = "ALPM Contributors"
SPDX-License-Identifier = "CC-BY-SA-4.0"
path = [
    "**.md",
    "alpm-lint-website/**/*.css",
    "alpm-lint-website/**/*.html",
    "alpm-lint-website/**/*.js",
    "alpm-lint-website/**/*.scss",
    "alpm-lint-website/static/icons/*.ico",
    "alpm-lint-website/static/icons/*.png",
]
precedence = "aggregate"
