[book]
authors = ["Arne Beer", "David Runge", "Orhun ParmaksÄ±z"]
language = "en"
src = "src"
title = "ALPM"

[build]
build-dir = "../../output/docs"
create-missing = false

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["mermaid-init.js", "mermaid.min.js"]
git-repository-icon = "fa-code-fork"
git-repository-url = "https://gitlab.archlinux.org/archlinux/alpm/alpm"
